### ISSUE TITLE
issue when using hapi-async-handler

### ISSUE THREAD

**Issue by jamesdixon** [devinivy/haute-couture#25]
Me again 👍 

I'm trying to use the [hapi-async-handler](https://github.com/ide/hapi-async-handler) package to allow usage of `async` handlers:

Handler code:

```js
'use strict';

const Member = require('../models/member');

module.exports = {

    async fetchAll(request, reply) {
        return reply();
    }
};
```

Route code:

```js
'use strict';

const Handler = require('../handlers/member');

module.exports = [
    {
        method: 'get',
        path: '/members',
        handler: {
            async: Handler.fetchAll
        }
    }
];
```

Resulting error:

```
/Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:148
        throw internals.tagError(err, call);
        ^

Error: instance.route() called by haute using /Users/jamesdixon/Projects/healthgenie/api/lib/routes/member.js: Unknown handler: async
    at Object.exports.assert (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.defaults (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hapi/lib/handler.js:111:14)
    at new module.exports.internals.Route (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hapi/lib/route.js:60:37)
    at module.exports.internals.Connection.internals.Connection._addRoute (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hapi/lib/connection.js:411:19)
    at module.exports.internals.Connection.internals.Connection._route (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hapi/lib/connection.js:403:18)
    at module.exports.internals.Plugin.internals.Plugin._apply (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hapi/lib/plugin.js:588:14)
    at module.exports.internals.Plugin.internals.Plugin.route (/Users/jamesdixon/Projects/healthgenie/api/node_modules/hapi/lib/plugin.js:558:10)
    at Object.internals.callMethod (/Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:145:16)
    at Items.serial (/Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:130:23)
    at iterate (/Users/jamesdixon/Projects/healthgenie/api/node_modules/items/lib/index.js:36:13)
    at done (/Users/jamesdixon/Projects/healthgenie/api/node_modules/items/lib/index.js:28:25)
    at Items.serial (/Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:133:17)
    at iterate (/Users/jamesdixon/Projects/healthgenie/api/node_modules/items/lib/index.js:36:13)
    at done (/Users/jamesdixon/Projects/healthgenie/api/node_modules/items/lib/index.js:28:25)
    at Items.serial (/Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:133:17)
    at iterate (/Users/jamesdixon/Projects/healthgenie/api/node_modules/items/lib/index.js:36:13)
```

I use it with my other project, which doesn't use `haute-couture` and it works as expected. 

FWIW, I also tried your `toys` package, using the following code:

```js
'use strict';

const Handler = require('../handlers/member');
const Toys = require('toys');

module.exports = [
    {
        method: 'get',
        path: '/members',
        handler: Toys.handler(Handler)
    }
];

```

but I receive the following error:

```
/Users/jamesdixon/Projects/healthgenie/api/node_modules/toys/lib/index.js:383
    const methodParts = notation.match(/^([\w\.]+)(?:\s*)(?:(\()(?:\s*)(\w+(?:\.\w+)*(?:\s*\,\s*\w+(?:\.\w+)*)*)?(?:\s*)\))?$/);
                                ^

TypeError: Cannot read property 'match' of undefined
    at Object.internals.fromString (/Users/jamesdixon/Projects/healthgenie/api/node_modules/toys/lib/index.js:383:33)
    at Function.handler (/Users/jamesdixon/Projects/healthgenie/api/node_modules/toys/lib/index.js:44:26)
    at Object.<anonymous> (/Users/jamesdixon/Projects/healthgenie/api/lib/routes/member.js:10:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireDir (/Users/jamesdixon/Projects/healthgenie/api/node_modules/require-dir/index.js:122:33)
    at manifest.forEach (/Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:37:29)
    at Array.forEach (native)
    at /Users/jamesdixon/Projects/healthgenie/api/node_modules/haute/lib/index.js:25:18
    at /Users/jamesdixon/Projects/healthgenie/api/node_modules/haute-couture/lib/index.js:27:20
    at Object.exports.register (/Users/jamesdixon/Projects/healthgenie/api/lib/index.js:8:25)
```

Any suggestions?

Thank you!
James

**Comment by jamesdixon** [comment]
Plugin registration order was the cause! My bad 😄

**Comment by devinivy** [comment]
No worries :)  Also, we'll be publishing some info on how to sidestep registration order issues before long!  Do you think that Toys still might have an issue?

**Comment by jamesdixon** [comment]
@devinivy I can't seem to reproduce the issue with Toys, so let's say it's good 👍  I'll let you know if it pops up again
